// DualShock 4 input: edge-triggered button events with repeat and acceleration for held
// directions, left-stick-as-d-pad with a deadzone and hysteresis (logic in input_logic.h).

#ifndef PS4IPTV_PLATFORM_INPUT_H
#define PS4IPTV_PLATFORM_INPUT_H

#include <vector>

#include "input_logic.h"

enum class PadButton {
    Up,
    Down,
    Left,
    Right,
    Cross,
    Circle,
    Square,
    Triangle,
    L1,
    R1,
    L2,
    R2,
    Options,
    Count
};

struct InputEvent {
    PadButton button;
    bool repeat = false;     // generated by holding the button
    int repeatCount = 0;     // 0 for the initial press
};

class InputManager {

public:

    // joystick: SDL_Joystick* of the first pad (may be null). now: seconds.
    void update(void *joystick, double now);

    const std::vector<InputEvent> &events() const { return pending; }

    bool held(PadButton b) const { return keys[(int) b].isDown(); }

private:

    input::KeyRepeater keys[(int) PadButton::Count];
    input::StickFilter stick;
    std::vector<InputEvent> pending;
};

// buttons that repeat while held (navigation, paging, keyboard backspace)
bool isRepeatable(PadButton b);

const char *buttonName(PadButton b);

#endif // PS4IPTV_PLATFORM_INPUT_H
