// Controller navigation logic without SDL (host-testable): key repeat with acceleration for held
// buttons, and a left-stick direction filter with hysteresis.

#ifndef PS4IPTV_PLATFORM_INPUT_LOGIC_H
#define PS4IPTV_PLATFORM_INPUT_LOGIC_H

namespace input {

    // Hold-to-scroll timings (seconds). First press moves at once; repeats start after initialDelay and
    // speed up the longer the button is held.
    struct RepeatTiming {
        double initialDelay = 0.36;
        double interval = 0.100;        // until fastAfter
        double fastAfter = 1.5;
        double fastInterval = 0.065;    // until turboAfter
        double turboAfter = 3.5;
        double turboInterval = 0.050;
    };

    // repeat interval for a button held for `heldFor` seconds
    double repeatInterval(const RepeatTiming &timing, double heldFor);

    enum class KeyEvent {
        None,
        Press,     // the button went down
        Repeat     // generated by holding it
    };

    // One button. update() is called every frame with the current state and emits at most one event, so a
    // long frame never produces a burst of repeats (no runaway scrolling after a hitch).
    class KeyRepeater {

    public:

        explicit KeyRepeater(const RepeatTiming &timing = RepeatTiming()) : timing(timing) {}

        KeyEvent update(bool isDown, double now, bool repeatable);

        bool isDown() const { return down; }

        int repeatCount() const { return repeats; }

    private:

        RepeatTiming timing;
        bool down = false;
        double pressedAt = 0;
        double nextAt = 0;
        int repeats = 0;
    };

    enum class StickDir {
        None,
        Up,
        Down,
        Left,
        Right
    };

    // Left stick to one d-pad direction. A direction engages beyond ENGAGE on the dominant axis and is kept
    // until the stick falls below RELEASE on that axis (hysteresis: no flicker around the threshold).
    // Moving the stick into another direction switches immediately; returning near the centre releases it.
    class StickFilter {

    public:

        static const int ENGAGE = 16000;    // of 32767 (~49%)
        static const int RELEASE = 10000;   // ~31%

        StickDir update(int x, int y);

        StickDir current() const { return dir; }

    private:

        StickDir dir = StickDir::None;
    };
}

#endif // PS4IPTV_PLATFORM_INPUT_LOGIC_H
