// Controller navigation logic without SDL (host-testable): key repeat with acceleration for held
// buttons, and a left-stick direction filter with hysteresis.

#ifndef PS4IPTV_PLATFORM_INPUT_LOGIC_H
#define PS4IPTV_PLATFORM_INPUT_LOGIC_H

namespace input {

    // Hold-to-scroll timings (seconds). The first press moves at once; repeats start after initialDelay and
    // speed up the longer the button is held, stage by stage:
    //   0.30 - 1.0 s: every 90 ms, 1.0 - 2.0 s: 60 ms, 2.0 - 3.5 s: 40 ms, then 30 ms (~33 steps/s).
    // At most one step per frame is ever produced (KeyRepeater), so the 30 ms stage simply runs at the frame
    // rate on a slower frame and never queues steps.
    struct RepeatTiming {
        struct Stage {
            double until;      // held for less than this many seconds
            double interval;
        };

        static const int STAGES = 4;

        double initialDelay = 0.30;
        Stage stages[STAGES] = {{1.0, 0.090}, {2.0, 0.060}, {3.5, 0.040}, {1e9, 0.030}};
    };

    // repeat interval for a button held for `heldFor` seconds
    double repeatInterval(const RepeatTiming &timing, double heldFor);

    enum class KeyEvent {
        None,
        Press,     // the button went down
        Repeat     // generated by holding it
    };

    // One button. update() is called every frame with the current state and emits at most one event, so a
    // long frame never produces a burst of repeats (no runaway scrolling after a hitch). Releasing stops at
    // once: nothing is queued.
    class KeyRepeater {

    public:

        explicit KeyRepeater(const RepeatTiming &timing = RepeatTiming()) : timing(timing) {}

        // speed > 1 shortens the repeat intervals (full stick deflection); the initial delay is unchanged
        KeyEvent update(bool isDown, double now, bool repeatable, double speed = 1.0);

        bool isDown() const { return down; }

        int repeatCount() const { return repeats; }

        // seconds the button has been held (0 when up)
        double heldFor(double now) const { return down ? now - pressedAt : 0; }

    private:

        RepeatTiming timing;
        bool down = false;
        double pressedAt = 0;
        double nextAt = 0;
        int repeats = 0;
    };

    enum class StickDir {
        None,
        Up,
        Down,
        Left,
        Right
    };

    // Left stick to one d-pad direction. A direction engages beyond ENGAGE on the dominant axis and is kept
    // until the stick falls below RELEASE on that axis (hysteresis: no flicker around the threshold).
    // Moving the stick into another direction switches immediately; returning near the centre releases it.
    // Pushed nearly all the way (FAST_ENGAGE, kept until below FAST_RELEASE) the stick scrolls faster.
    class StickFilter {

    public:

        static const int ENGAGE = 16000;         // of 32767 (~49%)
        static const int RELEASE = 10000;        // ~31%
        static const int FAST_ENGAGE = 27000;    // ~82%
        static const int FAST_RELEASE = 24000;   // ~73%
        static constexpr double FAST_SPEED = 1.35;   // repeat speed factor while fast

        StickDir update(int x, int y);

        StickDir current() const { return dir; }

        // pushed nearly all the way in the current direction
        bool fast() const { return isFast; }

        // repeat speed factor for the direction the stick drives (1 or FAST_SPEED)
        double speed() const { return isFast ? FAST_SPEED : 1.0; }

    private:

        StickDir dir = StickDir::None;
        bool isFast = false;
    };
}

#endif // PS4IPTV_PLATFORM_INPUT_LOGIC_H
