// DualShock 4 input: edge-triggered button events with repeat and acceleration for held
// directions, left-stick-as-d-pad with a deadzone.

#ifndef PS4IPTV_PLATFORM_INPUT_H
#define PS4IPTV_PLATFORM_INPUT_H

#include <vector>

enum class PadButton {
    Up,
    Down,
    Left,
    Right,
    Cross,
    Circle,
    Square,
    Triangle,
    L1,
    R1,
    L2,
    R2,
    Options,
    Count
};

struct InputEvent {
    PadButton button;
    bool repeat = false;     // generated by holding the button
    int repeatCount = 0;     // 0 for the initial press
};

class InputManager {

public:

    // joystick: SDL_Joystick* of the first pad (may be null). now: seconds.
    void update(void *joystick, double now);

    const std::vector<InputEvent> &events() const { return pending; }

    bool held(PadButton b) const { return down[(int) b]; }

private:

    bool down[(int) PadButton::Count] = {};
    double pressedAt[(int) PadButton::Count] = {};
    double nextRepeat[(int) PadButton::Count] = {};
    int repeats[(int) PadButton::Count] = {};
    std::vector<InputEvent> pending;
};

const char *buttonName(PadButton b);

#endif // PS4IPTV_PLATFORM_INPUT_H
